### PR TITLE
update CI docker-compose file

### PR DESCRIPTION
**Pull request by konrad-sol**
Changing the setting of docker network to not be external.
Right now network is not created and tests are failing

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/65/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3188955287)

**Review by padiazg — APPROVED** [review]
LGTM

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3202912127)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3217492866)

**Pull request merged**
