### PR TITLE
selenium grid

### PR DESCRIPTION
**Pull request by konrad-sol**

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2877133625)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit:  
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2877133613)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 4d48d30e1cb25f30952d997333d0baa825837844 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2881339450)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 4d48d30e1cb25f30952d997333d0baa825837844 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2881339458)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 0bef7a2f8ca335ca030ca0cc551b9891b00dece2 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882045284)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 0bef7a2f8ca335ca030ca0cc551b9891b00dece2 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882045283)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: ed87116aeaf9b2cbafa74ea507e4f21315e0e1b9 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882176514)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: ed87116aeaf9b2cbafa74ea507e4f21315e0e1b9 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882176507)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: b7d0560b6a3e3c11663bc551c76177bc18f00887 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882231857)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: b7d0560b6a3e3c11663bc551c76177bc18f00887 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2882231856)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 919428e6fffa16a550246d62935bc48b9fa8cb1d 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2888543854)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: 919428e6fffa16a550246d62935bc48b9fa8cb1d 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2888543857)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 41785bdc87bc018ca9192595ee1c7ba6e6794ad3 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2992020446)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 41785bdc87bc018ca9192595ee1c7ba6e6794ad3 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2992020447)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: f4683a53275c409956fdc68409aff22ff09c2c36 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2999238719)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: f4683a53275c409956fdc68409aff22ff09c2c36 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2999238718)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: f4683a53275c409956fdc68409aff22ff09c2c36 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/2999238718)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: 66e83ba55305002da3bb7180de32cf6182ef2a9e 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3006489276)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: bab4b7637aa4831827fb7bcdf6808de4df3c4d65 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3006582199)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: bab4b7637aa4831827fb7bcdf6808de4df3c4d65 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3006582202)

**Comment by Tyk-ITS** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: ae40ef05faf3734e730f6a1efef2c1fb36bc74f6 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3007348044)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/pull/62/merge
Commit: 3ef726f3d210e0f3cad8103aab95ecb84dfbe862 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3007387976)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 3ef726f3d210e0f3cad8103aab95ecb84dfbe862 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3007387975)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: fcc8c3e7436ce1c83f93947691f89106103855c3 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3008124995)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: af0c14404028fc3147a92898883f22e9d9853209 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3008227111)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 4cee635f65069715a9deeb31647bdff24572096c 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3008257248)

**Comment by Tyk-ITS** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: 4cee635f65069715a9deeb31647bdff24572096c 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3008257241)

**Comment by buger** [comment]
**UI tests result: success** :white_check_mark: 
Branch used: refs/pull/62/merge
Commit: bcefcd57172e7c027190d29598dee2dec00f1986 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3037005732)

**Comment by buger** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/main
Commit: 12fb8df438518c1c1e3ec148b945d344ac963d81 selenium grid
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3044526452)

**Comment by buger** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit: 12fb8df438518c1c1e3ec148b945d344ac963d81 selenium grid
Triggered by: push (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3044526459)

**Comment by buger** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: main
Commit: d2738d09aef399be8ae9a96328ec821b95b77b5c 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3044533171)

**Comment by buger** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: main
Commit: d2738d09aef399be8ae9a96328ec821b95b77b5c 
Triggered by: pull_request (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3044533171)

**Pull request merged**
