### PR TITLE
Added Pump to tyk_dashboard.yaml compose file

### PR DESCRIPTION
**Pull request by padiazg**
Added Pump to tyk_dashboard.yaml compose file, so metrics are collected with this stack.

### CODE REVIEW

**Comment by Tyk-ITS** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: refs/pull/64/merge
Commit:  
Triggered by: pull_request (@padiazg)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3063938324)

**Review by konrad-sol — APPROVED** [review]

**Comment by Tyk-ITS** [comment]
**UI tests result: skipped** :no_entry_sign: 
Branch used: refs/heads/main
Commit: 68292b4ced6f73552f4a276daeb12d758c557dce Added Pump to tyk_dashboard.yaml compose file
Triggered by: push (@padiazg)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3067566512)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit: 68292b4ced6f73552f4a276daeb12d758c557dce Added Pump to tyk_dashboard.yaml compose file
Triggered by: push (@padiazg)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3067566513)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3141527563)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3156963856)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3172237025)

**Comment by Tyk-ITS** [comment]
**UI tests result: failure** :no_entry_sign: 
Branch used: refs/heads/main
Commit:  
Triggered by: schedule (@konrad-sol)
[Execution page](https://github.com/TykTechnologies/portal-tests/actions/runs/3187949532)

**Pull request merged**
